<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>To test Accomodation Availability for all CLS</description>
   <name>TestSuiteAccoAvbltyAllCls</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>cc3b0e0b-a653-46b4-8454-dddd06e74e91</testSuiteGuid>
   <testCaseLink>
      <guid>55c9342e-5d22-4166-a5ba-fa7b5fb3b0b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/TC_GetAllClsAccoAvblty_MCP</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7151b0c3-33ca-434e-a830-d5353b7e7cf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c15d6943-aba3-4799-9498-916993f2ccba</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b5bd3b5-6ec4-4ccc-a39d-c6d81c06af57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/TCGetAccAvblDD</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d523bee-c2ef-467c-9906-0a877cc4d782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc20ba1f-421d-47fb-aded-02f25e8f10a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89b32a5a-9892-4452-b0cc-b9ce4942f2f3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb66269a-7292-4204-8433-566fb0e4b087</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dfaae37-e47d-4281-98f9-c0f2500ceb75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34a121c6-7c90-4998-a940-916f35615b93</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
