<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>It will contain all the test cases related to FS_TC_CLIENT_BOOKING</description>
   <name>TestSuiteFS_TC_CLIENT_BOOKING</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>dd6fe57e-2b40-4cae-a747-b5b4856665b9</testSuiteGuid>
   <testCaseLink>
      <guid>462ff812-91f4-4fac-9d18-1a5cfadabbd4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC_CL_NORMAL_BKG_12_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc65eccf-5793-4e1d-9351-eefb669170d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a6b4b8d-8ab5-4d84-95d6-faf9c23a1293</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a9c8292-2ff0-4cc1-bee8-ab6643332471</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70e06ad4-c525-4ff7-bc9a-611d048e3d06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c466f444-c0d4-4bae-8eba-7abed1621c09</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4fe41a-4c7e-4761-b679-0ad0d309db84</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3c1b180-b1cb-4d79-9b55-60a759d05d31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC__CL_NORMAL_BKG_21_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18d4a9bd-5076-4195-b571-9bd07fada1de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd523174-6480-483b-af78-ed34f61fa656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ad0c847-5089-4c7e-82de-ac8deea195f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f98f86af-c60c-4141-9dad-b9ce7f7d0915</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>678c99e8-3fec-4601-84bb-5344be779f83</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12e3accc-3f13-4043-b13d-52059b1f3266</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34cda152-e742-406a-8061-8cdf4d33c679</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC_CL_NORMAL_BKG_22_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6295386-d55c-43f4-90b8-278343d40601</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41827200-f58f-42da-ad3b-1fc60d3ceb91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90c5e256-0c96-47e1-a74a-d5548b03f2f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0068cb4-87ab-44ec-bc01-9f23f87f68c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd5a6bca-7415-42f7-8464-ff7934c3e337</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c66d5da-a85c-4421-aa98-6cac619809d8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3604598e-e2f8-4bb1-b451-b8a0a7a97d55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC_CL_NORMAL_BKG_29_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe1269c9-273f-4899-aa53-fc2ab96ab6d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f42a9e2-61dd-4a45-a19d-599646c4aa2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7b9a026-ed6f-4742-8313-3ade21231e5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26d98e6e-da47-4a6b-bac9-a89e0d10e9cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d296a45-7b0f-4845-9608-8a416becb490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01845f84-a3c7-4373-81e7-985ef11aeb03</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>127a1fc6-0b83-4a9f-9062-fb30c55b6067</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC_CL_NORMAL_BKG_40_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b358497c-dbad-49a3-8d1f-6cc08dd2a715</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f4525db-49c7-490e-a958-f44a99991b40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f99956e8-5c44-4044-ac17-d108ade2c484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a810a63-5856-4fe7-ae71-5e26de9aec04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cc45284-a514-4d76-92a8-fbd033b36f3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb1d7144-520d-4873-948a-3714a6023c34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4d9bfcb-d157-425c-add4-fae5e3494dd2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC__CL_NORMAL_BKG_42_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c97479c4-3e5f-4309-babf-7e442bbc5dec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1083ee35-d692-484a-a80f-a9f1b086a86c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7623dca-ddf8-479f-816c-02312830d4f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5bea901-b93b-445b-a2aa-cfea60de781a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9d55464-4f40-4d62-b8bd-167a051cfbd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e6f1da0-ba85-4e27-847b-3e8b07f62cf1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7daa1dd2-d471-43b9-86d7-2e6e5c48ee6e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC__CL_NORMAL_BKG_43_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>62c51230-a1cb-4a62-a56d-6e7dfff692be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33397fa4-09a4-498c-a303-90e2980dca80</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b7f2ed4-30d4-43b0-9f31-991ea13ce36a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a4b533a-61c8-4ccc-88f1-a88abe0c2851</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b234af4-5e10-4058-b6bd-2836c927c9d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75ad34e1-4352-4db9-90b8-aa6c812ac81c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d93ce43-293b-4897-a073-fc68346c6546</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ClientTestCases/FS_TC_CLIENT_BOOKING/TC__CL_NORMAL_BKG_44_01</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddeb0b96-1647-41fe-b095-77fe7b19d6c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0f40788-13dc-4ada-ab47-f26c9e8c752a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f789126-978d-4225-8d33-ad7c87c2daf7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3650b0eb-f8f4-47f1-adcb-a43431dceb04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26304991-c8c6-40ab-b796-9630d5e6e335</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a4974e0-cb6e-443c-a7d2-845e6fa61992</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
