<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_completePsgnDetails</name>
   <tag></tag>
   <elementGuidId>78787538-4886-4bee-8d1b-c57e0c2bdadf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divMain']/app-enquiries/mat-sidenav-container/mat-sidenav-content/app-current-status/div/div/app-enq-psng-details/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body table-responsive  text-dark px-4 py-2 text-sm</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S.No. NameAgeGenderQuotaBooking StatusCurrent StatusConcessionCoach Position from EngineCoachBerth NoBerth TypeCoachBerth NoBerth Type01PASS ONE43MGNA3,37 LBA3,37 LB002PASS TWO43FGNA3,38 UBA3,38 UB003PASS THREE34MGNA3,39 LBA3,39 LB004PASS FOUR34TGNA3,40 UBA3,40 UB005PASS FIVE43MGNA3,42 SUA3,42 SU006PASS SIX43TGNA3,29 SLA3,29 SL0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMain&quot;)/app-enquiries[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;bg-theme mat-drawer-container mat-sidenav-container mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content ng-untouched ng-pristine ng-valid&quot;]/app-current-status[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-enq-psng-details[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card bg-theme  mat-elevation-z4 my-3&quot;]/div[@class=&quot;card-body table-responsive  text-dark px-4 py-2 text-sm&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMain']/app-enquiries/mat-sidenav-container/mat-sidenav-content/app-current-status/div/div/app-enq-psng-details/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Passenger Details'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expected Arrival : 03:57 (2 min late)'])[1]/following::div[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-enq-psng-details/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
