<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SubmitStockDetails</name>
   <tag></tag>
   <elementGuidId>c9d3db49-1d77-4431-92fc-09fe6bf2ef48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;divMain&quot;]/app-login/div/div/div[2]/app-stock-entry/div/form/div[7]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;divMain&quot;)/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid px-4&quot;]/div[@class=&quot;row mb-5&quot;]/div[@class=&quot;col-12 col-sm-6 col-lg-4 col-xl-3 my-5 mat-elevation-z8 bg-gradient-primary-accent p-0 mx-auto&quot;]/app-stock-entry[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;m-2 bg-theme&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10 mx-auto my-3&quot;]/button[@class=&quot;font-weight-bold w-100 mat-raised-button mat-accent&quot;][count(. | //button[@class = 'font-weight-bold w-100 mat-raised-button mat-accent' and (text() = 'Submit' or . = 'Submit')]) = count(//button[@class = 'font-weight-bold w-100 mat-raised-button mat-accent' and (text() = 'Submit' or . = 'Submit')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold w-100 mat-raised-button mat-accent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>accent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMain&quot;)/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid px-4&quot;]/div[@class=&quot;row mb-5&quot;]/div[@class=&quot;col-12 col-sm-6 col-lg-4 col-xl-3 my-5 mat-elevation-z8 bg-gradient-primary-accent p-0 mx-auto&quot;]/app-stock-entry[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;m-2 bg-theme&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-10 mx-auto my-3&quot;]/button[@class=&quot;font-weight-bold w-100 mat-raised-button mat-accent&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMain']/app-login/div/div/div[2]/app-stock-entry/div/form/div[7]/div/button</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User ID'])[1]/following::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last-Stock Roll Used'])[1]/preceding::button[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
   </webElementXpaths>
</WebElementEntity>
