<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_BerthPreference1</name>
   <tag></tag>
   <elementGuidId>0d5a4aa0-a779-4a02-afd6-ed8d3a2daa04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]/mat-form-field[6]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c138-62</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No PreferenceBerth Preference</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-1&quot;)/app-passenger-list[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;card-body py-1 px-4 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;ng-star-inserted&quot;]/app-passenger[@class=&quot;row ng-tns-c275-53&quot;]/div[@class=&quot;row card bg-theme mat-elevation-z4 my-1 mx-0 pb-3 w-100 ng-tns-c275-53 ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;row pb mt-2 px-3 ng-tns-c275-53&quot;]/mat-form-field[@class=&quot;mat-form-field col-md-2 col-sm-4 col-12 ng-tns-c275-53 ng-tns-c138-62 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-pristine ng-valid mat-form-field-should-float ng-touched&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c138-62&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c138-62&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c138-62&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-1']/app-passenger-list/form/div/app-passenger/div/div[2]/mat-form-field[6]/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child Berth'])[2]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Child Berth'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/mat-form-field[6]/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
