<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total_AccAvbl_MsgFetched</name>
   <tag></tag>
   <elementGuidId>7058eba5-09db-497a-8594-ce3a8fd85777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-availability-output-all/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card bg-theme mat-elevation-z4 my-2 table-responsive</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DateSECOND AC-2A Sat, Jun 6, 2020  RAC   7/RAC   7  Sun, Jun 7, 2020  RAC   3/RAC   3  Mon, Jun 8, 2020  RAC   6/RAC   6  Tue, Jun 9, 2020  AVAILABLE-0003  Wed, Jun 10, 2020  AVAILABLE-0006  Thu, Jun 11, 2020  RAC   2/RAC   2  Fri, Jun 12, 2020  RAC  10/RAC  10  Sat, Jun 13, 2020  AVAILABLE-0002  Sun, Jun 14, 2020  AVAILABLE-0021  Mon, Jun 15, 2020  AVAILABLE-0021  Tue, Jun 16, 2020  AVAILABLE-0021  Wed, Jun 17, 2020  AVAILABLE-0021  Thu, Jun 18, 2020  AVAILABLE-0021  Fri, Jun 19, 2020  AVAILABLE-0021 </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divMain&quot;)/app-enquiries[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container bg-transparent ng-star-inserted mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content ng-untouched ng-pristine ng-valid&quot;]/app-accomodation-availability[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container&quot;]/app-availability-output-all[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;card bg-theme mat-elevation-z4 my-2 table-responsive&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divMain']/app-enquiries/mat-sidenav-container/mat-sidenav-content/app-accomodation-availability/div/app-availability-output-all/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fetch Availability'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-availability-output-all/div</value>
   </webElementXpaths>
</WebElementEntity>
